# Generated by Django 5.0.6 on 2024-06-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='M', max_length=1)),
                ('fechaNacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=10)),
                ('idEmpleado', models.AutoField(primary_key=True, serialize=False)),
                ('tipoEmpleado', models.CharField(choices=[('MASAJISTA', 'MASAJISTA'), ('RECEPCIONISTA', 'RECEPCIONISTA'), ('LIMPIEZA', 'LIMPIEZA'), ('COCINA', 'COCINA'), ('SEGURIDAD', 'SEGURIDAD'), ('MANTENIMIENTO', 'MANTENIMIENTO'), ('VALET', 'VALET'), ('CAMARERO', 'CAMARERO')], default='MASAJISTA', max_length=15)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
