# Generated by Django 5.0.6 on 2024-06-04 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=100)),
                ('genero', models.BooleanField(default=False)),
                ('fechaNacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=10)),
                ('idHuesped', models.AutoField(primary_key=True, serialize=False)),
                ('tipoCliente', models.CharField(choices=[('VIP', 'VIP'), ('ESTANDAR', 'ESTANDAR'), ('NUEVO', 'NUEVO'), ('FRECUENTE', 'FRECUENTE')], default='NUEVO', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('nroTarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('fechaExpiracion', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('huesped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjeta', to='Huespedes.huesped')),
            ],
        ),
    ]
