# Generated by Django 5.0.6 on 2024-06-04 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Huespedes', '0003_alter_huesped_tarjeta'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huesped',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='huesped',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='huesped',
            name='email',
        ),
        migrations.RemoveField(
            model_name='huesped',
            name='fechaNacimiento',
        ),
        migrations.RemoveField(
            model_name='huesped',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='huesped',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='huesped',
            name='telefono',
        ),
        migrations.AddField(
            model_name='huesped',
            name='persona',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='persona_huesped', to='core.persona'),
        ),
    ]
