# Generated by Django 5.0.6 on 2024-06-04 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0003_remove_empleado_persona_empleado_apellido_and_more'),
        ('Huespedes', '0005_remove_huesped_persona_huesped_apellido_huesped_dni_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
