# Generated by Django 5.0.6 on 2024-06-04 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Reservas', '0003_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='facturas', to='Reservas.reserva')),
                ('servicioList', models.ManyToManyField(related_name='facturas', to='Reservas.servicio')),
            ],
        ),
    ]
