# Generated by Django 5.0.6 on 2024-06-04 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0001_initial'),
        ('Reservas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='empleado_list',
        ),
        migrations.AddField(
            model_name='servicio',
            name='empleado_list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='servicios', to='Empleados.empleado'),
        ),
    ]
