# Generated by Django 5.0.6 on 2024-06-04 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0004_alter_habitacion_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='habitacionList',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='reserva',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='habitacionList', to='Reservas.reserva'),
        ),
    ]
