# Generated by Django 5.0.6 on 2024-06-04 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0005_remove_reserva_habitacionlist_habitacion_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='reserva',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='habitacionList', to='Reservas.reserva'),
        ),
    ]
