# Generated by Django 5.0.6 on 2024-06-05 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0006_alter_habitacion_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='reserva',
        ),
        migrations.AddField(
            model_name='reserva',
            name='habitacionList',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservas', to='Reservas.habitacion'),
        ),
    ]
