# Generated by Django 5.0.6 on 2024-06-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0007_remove_habitacion_reserva_reserva_habitacionlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='habitaciones'),
        ),
    ]
