# Generated by Django 5.0.6 on 2024-06-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0008_habitacion_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='imagen',
            field=models.URLField(blank=True, default='https://th.bing.com/th/id/R.aa826c4a6e33b35a5da84f2a987412d0?rik=H%2bmTxTshNQRzeg&pid=ImgRaw&r=0', null=True),
        ),
    ]
