# Generated by Django 5.0.6 on 2024-06-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0009_alter_habitacion_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='descripcion',
            field=models.TextField(default='Habitacion sencilla'),
        ),
    ]
