# Generated by Django 5.0.6 on 2024-06-05 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0011_alter_habitacion_tipohabitacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='habitacionList',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='reserva',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='habitacionList', to='Reservas.reserva'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='habitaciones',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservas_habitacion', to='Reservas.habitacion'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='servicioList',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservas_servicio', to='Reservas.servicio'),
        ),
    ]
