# Generated by Django 5.0.6 on 2024-06-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0012_remove_reserva_habitacionlist_habitacion_reserva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(default='Servicio de comida a Habitación. Servicio rapido y de calidad'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='imagen',
            field=models.URLField(blank=True, default='https://www.abasturhub.com/img/blog/roomservice-op1_-roomservice-con-serv--1-.jpg', null=True),
        ),
    ]
