# Generated by Django 5.0.6 on 2024-06-05 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0013_servicio_descripcion_servicio_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='reserva',
        ),
    ]
